source:
  reader: iceberg_with_partition
  catalog_name: nybike_catalog
  database: silver
  dbtable: trip_data_nybike
  column_partition: dw_period_tag
  value_partition: TBD

target:
  sinker: merging_data
  catalog_name: nybike_catalog
  database: silver
  dbtable: trip_data_nybike
  branch_source: TBD
  branch_target: main

dq_conf:
  rows_count_check:
    expected_rows_count: TBD
  null_check:
    column_list_check_null: ["trip_uuid", "start_at", "stop_at"]
  properties_audit:
    process_status_faillure: FAILED
    process_status_success: SUCCESS
    catalog_name: nybike_catalog

  properties_data_dq:
    process_name: "DQ_TO_SILVER_LAYER"
    process_status_faillure: FAILED_TO_PUBLISH_SILVER_LAYER
    process_status_success: TO_GOLD_LAYER
    process_status: TO_PUBLISH_SILVER_LAYER
