FROM python:3.12.9-bullseye AS spark-base

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      sudo \
      curl \
      vim \
      unzip \
      rsync \
      openjdk-17-jdk \
      scala \
      git \
      build-essential \
      software-properties-common \
      ssh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV POETRY_VERSION="2.4.1"
ENV APP_HOME=/app_config
ENV SPARK_VERSION="4.2.0"
ENV SPARK_HOME=/opt/spark
ENV HADOOP_HOME=/opt/hadoop
ENV SPARK_MASTER_PORT=7077
ENV SPARK_MASTER_HOST=spark-master
ENV SPARK_MASTER="spark://$SPARK_MASTER_HOST:$SPARK_MASTER_PORT"
ENV PYTHONPATH=$SPARK_HOME/python/
ENV PYSPARK_PYTHON=python3
ENV IJAVA_CLASSPATH=/opt/spark/jars/*

RUN mkdir -p $HADOOP_HOME && mkdir -p $SPARK_HOME
WORKDIR $SPARK_HOME

RUN mkdir -p ${SPARK_HOME}
RUN curl https://dlcdn.apache.org/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz -o spark-${SPARK_VERSION}-bin-hadoop3.tgz 
RUN tar xvzf spark-${SPARK_VERSION}-bin-hadoop3.tgz --directory ${SPARK_HOME} --strip-components 1
RUN rm -rf spark-${SPARK_VERSION}-bin-hadoop3.tgz

RUN chmod u+x /opt/spark/sbin/* && \
    chmod u+x /opt/spark/bin/*
ENV PATH="$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin"

# Install Almond Scala kernel with stable version
ENV ALMOND_VERSION=0.14.4
ENV SCALA_VERSION=2.13.12

RUN curl -fL https://github.com/coursier/launchers/raw/master/coursier -o /usr/local/bin/coursier && \
    chmod +x /usr/local/bin/coursier && \
    /usr/local/bin/coursier launch --fork almond:${ALMOND_VERSION} -- --install --global

##################------------------##############

FROM spark-base AS pyspark

COPY base_images_services/spark_image/spark-defaults.conf $SPARK_HOME/conf/
COPY base_images_services/spark_image/ivysettings.xml $SPARK_HOME/conf/ivysettings.xml

RUN echo "spark_base image built with success"
RUN pip3 install poetry==$POETRY_VERSION

WORKDIR $APP_HOME

COPY project_etl_pipeline/pyproject.toml . 
COPY project_etl_pipeline/poetry.lock .

RUN poetry config virtualenvs.create false && \
    poetry config installer.max-workers 1 && \
    poetry install --with spark --no-root --no-interaction

##########------------------------##############
# Install Jupyter with Python and Scala kernels

FROM pyspark AS pyspark-jupyter

RUN poetry install --with sparkmaster --no-root --no-interaction

WORKDIR $APP_HOME

COPY base_images_services/spark_image/entrypoint.sh .
RUN chmod u+x entrypoint.sh

ENV JUPYTER_PORT=8889
ENV JUPYTER_ENABLE_LAB=yes

# Verify both kernels are installed
RUN jupyter kernelspec list

# EXPOSE ${JUPYTER_PORT}
# CMD ["jupyter", "lab", "--no-browser", "--allow-root", "--ip=0.0.0.0", "--port=8889"]

ENV PYSPARK_DRIVER_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON_OPTS="jupyter lab --no-browser --allow-root --ip=0.0.0.0 --port=${JUPYTER_PORT}"
