[tool.poetry]
name = "airflow-spark-project-datawarehouse-nybike"
version = "0.1.0"
description = ""
authors = ["BenOmar"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"

[tool.poetry.group.spark.dependencies]
pyspark = "3.5.6"
pydantic = "2.10.6"
psycopg2-binary = "2.9.10"

[tool.poetry.group.sparkmaster.dependencies]
notebook = "^7.3.3"
jupyterlab = "^4.4.7"

[tool.poetry.group.airflow.dependencies]
pyspark = "3.5.6"
apache-airflow-providers-apache-spark = "4.11.3"



[tool.poetry.group.dev.dependencies]
apache-airflow = "2.10.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
