[project]
name = "airflow-spark-project-datawarehouse-nybike"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyspark>=3.5.4",
    "sqlmodel>=0.0.22",
]
