# source:
#   url: "jdbc:postgresql://source-host:5432/db"
#   user: "user"
#   table : ""
#   driver: "org.postgresql.Driver"
#   table: "source_table"
#   sink: "database"

source :
  # reader : "ReaderCSVLocal"
  root_path : "/opt/airflow/include"
  process_step: STAGE_DATABASE

target:
  driver: "org.postgresql.Driver"
  sink: "database_table"
  url : "jdbc:postgresql://db:5432/postgres"
  user : "root"
  password : "your-password"
  mode : "append"

report:
  process_name : "ETL-NY-Process-Before-publish"
  report_type : "ny_bike_report"
  process_period : "ANNUAL"
  url: "jdbc:postgresql://db:5432/postgres"
  user: "root"
  dbtable: "REPORT_PROCESS"
  sink: "database_sql"
  password : "your-password"
  mode : "append"

etl_conf:
  columns_to_rename:
    tripduration: TRIP_DURATION
    starttime: START_AT
    stoptime: STOP_AT
    start station id: START_STATION_ID
    start station name: START_STATION_NAME
    start station latitude: START_STATION_LATITUDE
    start station longitude: START_STATION_LONGITUDE
    end station id: END_STATION_ID
    end station name: END_STATION_NAME
    end station latitude: END_STATION_LATITUDE
    end station longitude: END_STATION_LONGITUDE
    bikeid: BIKE_ID
    usertype: USER_TYPE
    birth year: CUSTOMER_YEAR_BIRTH
    rideable_type: RIDEABLE_TYPE
    started_at: START_AT
    ended_at: STOP_AT
    start_station_name: START_STATION_NAME
    start_station_id: START_STATION_ID
    end_station_name: END_STATION_NAME
    end_station_id: END_STATION_ID
    start_lat: START_STATION_LATITUDE
    start_lng: START_STATION_LONGITUDE
    end_lat: END_STATION_LATITUDE
    end_lng: END_STATION_LONGITUDE
    member_casual: CUSTOMER_TYPE
    gender: GENDER
  
  columns_to_delete : ["bikeid"]
  columns_for_ids :
    ids_columns :
      date_id_column : 'DATE_ID'
      station_id_column : 'TRIP_STATION_NYBIKE_ID'
      fact_id_column : 'FACT_ID'
    column_to_hash : ['TRIP_DURATION','START_AT','STOP_AT','START_STATION_LATITUDE','START_STATION_LONGITUDE','END_STATION_LATITUDE','END_STATION_LONGITUDE','RIDEABLE_TYPE']

  dimensions_time :  
    datetime_column : 'START_AT'