spark:
  executor:
    memory: "4g"
    cores: "2"
  sql:
    shuffle:
      partitions: "200"
  jars:
    packages: "org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.3.1,org.projectnessie.nessie-integrations:nessie-spark-extensions-3.3_2.12:0.67.0"
application_args:
  input_path: "/path/to/input"
  output_path: "/path/to/output"