# source:
#   reader: IcebergQuery
#   dbtable: warehouse.bronze.trip_data_nybike
#   query: select * from {} where dw_period_tag='{}'

# target:
#   schema: silver
#   sink: SinkDataToIceberg
#   mode: append
#   dbtable: warehouse.silver.trip_data_nybike

source:
  reader: iceberg_with_partition
  catalog_name: nybike_catalog
  database: bronze
  dbtable: trip_data_nybike
  column_partition: dw_period_tag
  value_partition: TBD

target:
  sinker: SinkDataToIceberg
  catalog_name: nybike_catalog
  database: silver
  mode: overwrite
  # mode: append
  dbtable: trip_data_nybike
  column_param_overwrite_name: dw_period_tag
  column_param_overwrite_value: TBD

etl_conf:
  diff_column:
    column_result: enr_trip_duration
    column_greather: stop_at
    colmun_lesser: start_at
    column_ancien: trip_duration
  dimensions_time:
    datetime_column: start_at
  column_id: trip_uuid
  cast_to_timestamp: ["start_at", "stop_at"]
  value_for_fill: n/a

  properties_audit:
    process_status_faillure: FAILED
    process_status_success: SUCCESS
    catalog_name: nybike_catalog

  properties_data_etl:
    process_name: "ETL_TO_SILVER_LAYER"
    process_status_faillure: FAILURE_TO_SILVER_LAYER
    process_status_success: TO_PUBLISH_SILVER_LAYER
    process_status: TO_SILVER_LAYER
